### ISSUE TITLE
Feature request: support MAC container

### ISSUE THREAD

**Issue by glureau** [maheshrayas/action-pr-comment-delete#3]
Looks like this plugin only supports Linux :
![image](https://user-images.githubusercontent.com/7968075/141017053-940508ed-b163-489c-bb05-a5b610dd3fce.png)

**Comment by maheshrayas** [comment]
Thanks for the feature request @glureau. You should be able to use v2.0 which would support macOS and Windows runners. 
https://github.com/maheshrayas/action-pr-comment-delete/tree/mac-windows

**Comment by glureau** [comment]
Ah thank you!

I finally found another plugin [sticky-pull-request-comment](https://github.com/marketplace/actions/sticky-pull-request-comment) dealing with comment+remove previous (that was my initial need) and supporting MAC.

Thanks for your work!
